#!/bin/bash

WORKDIR="${HOME}/GPU_Malloc"
PYTHON_BIN="${HOME}/anaconda3/bin/python"

export PYTHON_BIN_PATH="${PYTHON_BIN}"
export PYTHON_LIB_PATH="${HOME}/anaconda3/lib/python3.5/site-packages"
export TF_NEED_JEMALLOC=1
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_AWS=0
export TF_NEED_KAFKA=0
export TF_ENABLE_XLA=0
export TF_NEED_GDR=0
export TF_NEED_VERBS=0
export TF_NEED_NGRAPH=0
export TF_NEED_OPENCL_SYCL=0
export TF_NEED_CUDA=1
export TF_NEED_TENSORRT=0
export TF_NEED_MPI=0

export GCC_HOST_COMPILER_PATH="$(which gcc)"
export CUDA_TOOLKIT_PATH="/usr/local/cuda"
export TF_CUDA_VERSION="9.0"
export CUDNN_INSTALL_PATH="/usr/local/cuda"
export TF_CUDNN_VERSION="7"
export TF_NCCL_VERSION="1.3"
export TF_CUDA_COMPUTE_CAPABILITIES="3.0"
export TF_CUDA_CLANG=0
export CC_OPT_FLAGS="-mcpu=native"
export TF_SET_ANDROID_WORKSPACE=0

cd "${WORKDIR}"/tensorflow/

./configure

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

#${PYTHON_BIN} -m pip install /tmp/tensorflow_pkg/tensorflow-versio*
